---
- name: Setup Jenkins Agent
  hosts: jenkins_agent
  become: yes
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Java 21
      apt:
        name: openjdk-21-jre
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Add jenkins user to docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Set permissions for Docker socket
      file:
        path: /var/run/docker.sock
        mode: '0666'

    - name: Install Trivy
      shell: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      args:
        creates: /usr/local/bin/trivy
